#!/bin/bash
#SBATCH --job-name=zl_heatmap
#SBATCH --partition=batch
#SBATCH --mail-type=ALL
#SBATCH --mail-user=seg75580@uga.edu
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=24
#SBATCH --mem=20gb
#SBATCH --time=1:00:00
#SBATCH --output=heatmap.%j.out
#SBATCH --error=heatmap.%j.err

cd $SLURM_SUBMIT_DIR

ml deepTools/3.5.5-gfbf-2023a
OUTDIR="/scratch/seg75580/Run147/bowtieSbatch-cyp51A"

mkdir "${OUTDIR}/SortedRegions"
##you want to run in reference point mode
## your reference point will be the transcription start site (TSS)

##relevant info
##-p number of processors
#-R regions - you will be using a gtf, because your regions are genes (more specifically, the start of genes)
#-S score file - these will be your bigwig files; you can give all your samples at once


##https://deeptools.readthedocs.io/en/develop/content/tools/computeMatrix.html
####Plotting scaled enrichment across all het domains

computeMatrix reference-point -S BIGWIG FILE PATH -R GTF FILE PATH -a 1000 -b 1000 --referencePoint TSS \
              --outFileSortedRegions 'Run147_N21_P3.SortedRegions.txt' \
                -o 'Run147_N21_P3.matrix' \
                --sortRegions keep \
                --skipZeros \
                --missingDataAsZero \
                -bs 10
#https://deeptools.readthedocs.io/en/develop/content/tools/plotHeatmap.html
plotHeatmap -m 'Run147_N21_P3.matrix'\
        -o 'Run147_N21_P3.pdf' \
                --sortRegions descend  \
                        --sortUsing sum \
                        --heatmapHeight 15 \
                        --zMax 0.10 \
                        --outFileSortedRegions 'Run147_N21_P3.SortedRegions.txt' \
